# -*- coding: utf-8 -*-
"""UASCC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1emy_9LVG4YrXctrybWA5ZhA-acvkx86k
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/reddit_final_text.csv")

!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()

def get_sentiment(text):
    if not isinstance(text, str):  # Cek apakah text adalah string
        return "neutral"
    score = analyzer.polarity_scores(text)
    compound = score['compound']
    if compound >= 0.05:
        return "positive"
    elif compound <= -0.05:
        return "negative"
    else:
        return "neutral"

df["sentiment_label"] = df["clean_text"].apply(get_sentiment)

# Lihat persentase hasil
print(df["sentiment_label"].value_counts(normalize=True) * 100)

# Menampilkan 5 contoh kalimat positif
print("Contoh kalimat POSITIVE:")
print(df[df["sentiment_label"] == "positive"]["clean_text"].head(5).to_string(index=False))

# Menampilkan 5 contoh kalimat negatif
print("\nContoh kalimat NEGATIVE:")
print(df[df["sentiment_label"] == "negative"]["clean_text"].head(5).to_string(index=False))

# Menampilkan 5 contoh kalimat netral
print("\nContoh kalimat NEUTRAL:")
print(df[df["sentiment_label"] == "neutral"]["clean_text"].head(5).to_string(index=False))

"""# New Section"""